name: Kube_Container_Workflow
on: [push,workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        #login-server: contoso.azurecr.io
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker login docker.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build . -t docker.io/azurefunctionsimage:${{ github.sha }}
        docker push docker.io/azurefunctionsimage:${{ github.sha }} 
      
    - uses: AmrutaKawade/webapps-deploy@users/amkawade/lima-poc
      with:
        app-name: 'KubeConWebApp'
        images: 'docker.io/azurefunctionsimage:${{ github.sha }}'